### ISSUE TITLE
Error from within generator.lib.js when running command

### ISSUE THREAD

**Issue by FloNeu** [verizonconnect/ngx-form-generator#63]
I wanted to try out your project because it looks pretty neat - I think I got it set up correctly and have a valid swagger file freshly pulled from the API. But when I run the command I get: 
`
> ngx-form-generator -i apps/pdv-pwa/src/app/module/material-forms/nswag-pdv.swagger.json -o apps/pdv-pwa/src/app/module/material-forms/form

C:\Users\FloNeu_TP-X1E\ForgeTech\agrardata-pdv\frontend\node_modules\@verizonconnect\ngx-form-generator\dist\generator-lib.js:52
    const fields = Object.keys(definition.properties);
                          ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at makeFieldsBody (C:\Users\FloNeu_TP-X1E\ForgeTech\agrardata-pdv\frontend\node_modules\@verizonconnect\ngx-form-generator\dist\generator-lib.js:52:27)
    at makeDefinition (C:\Users\FloNeu_TP-X1E\ForgeTech\agrardata-pdv\frontend\node_modules\@verizonconnect\ngx-form-generator\dist\generator-lib.js:57:24)
    at C:\Users\FloNeu_TP-X1E\ForgeTech\agrardata-pdv\frontend\node_modules\@verizonconnect\ngx-form-generator\dist\generator-lib.js:86:21
    at Array.map (<anonymous>)
    at Object.makeForm (C:\Users\FloNeu_TP-X1E\ForgeTech\agrardata-pdv\frontend\node_modules\@verizonconnect\ngx-form-generator\dist\generator-lib.js:86:10)
    at main (C:\Users\FloNeu_TP-X1E\ForgeTech\agrardata-pdv\frontend\node_modules\@verizonconnect\ngx-form-generator\dist\generator-cli.js:40:34)
`

The swagger file i am getting is still on version 1.0 - can this be the problem?

Thx for building and taking a look at this. 
All the best!

**Comment by martinmcwhorter** [comment]
Unfortunately we only support version 2 and 3 of the Swagger spec. 

Is your Swagger file automatically generated from backend code? Can you update the libs to generate version 2 or 3?

**Comment by FloNeu** [comment]
I thought so - yes it's generated automatically from unity-framework
definitions - i guess it shouldn't be a big deal for them to finally update
to version 2 after (8?) years... but its external company. will definitely
request it. Thanks for the heads up

Am So., 16. Okt. 2022 um 09:55 Uhr schrieb Martin McWhorter <
***@***.***>:
